#!/usr/bin/env node
var chai = require("chai");
var expect = chai.expect;
var path = require("path");
var game = require('./the-game'); 
var entranceLocator = game.entranceLocator;
var readMap = game.readMap;
var whereCanIGo = game.whereCanIGo;
var howManyDoorsAreAvailable = game.howManyDoorsAreAvailable;
var whereDoesThatDirectionGo = game.whereDoesThatDirectionGo;
var treasureLocator = game.treasureLocator;

var gameLibrary = require('jsi-gamelib');
var fs = require('fs');
var readline = require('readline');

var rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

var showOptionsForRoom = function(map, room) {

  var directionOptions = whereCanIGo(room)
  var treasureRoom = treasureLocator(map);


  rl.question("What direction would you like to go?" + directionOptions, function(answer1) {
    var nextRoom = whereDoesThatDirectionGo(map, room, answer1);

    if (nextRoom === treasureRoom) {
      console.log('great job!');
      rl.close();
    }
    else {
      showOptionsForRoom(map, nextRoom);
    }
  });

};

readMap(process.argv[2], function(err, map) {
  var currentRoom = entranceLocator(map);
  showOptionsForRoom(map, currentRoom);
});
